[displaying]
length_displayed_stocks = 10
length_displayed_tweets = 3

[data_access]
path_to_index_symbols = "datasets/indices.csv"
path_to_stock_symbols = "datasets/stocks.csv"
path_to_datasets = "datasets/daily/"
fork_mode = "fork"

[twitter_api]
bearer_token = "AAAAAAAAAAAAAAAAAAAAAG8AhQEAAAAA4EckVEMHWEyM3rfxgNyiFTCy5hg%3DgSiAHWLHyAKtt9erA7l3dDMCgnQgoYifatBNcoUNrJUSh24D4w"



