version: "3"

services:
  webapp:
    container_name: webapp
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - "../:/app"
    tty: true
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M

  cronjob:
    container_name: cronjob
    build:
      context: ../
      dockerfile: docker/Dockerfile_cronjob
    restart: unless-stopped
    volumes:
      - "../:/app"
    tty: true
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
