FROM python:3.8

RUN echo 'alias ll="ls -al"' >> ~/.bashrc

RUN apt-get update && apt-get -y install cron

COPY ../ /app/
WORKDIR /app

RUN pip3 install -r requirements.txt
RUN pip3 install --editable .

COPY docker/crontab /etc/cron.d/crontab

RUN chmod 0644 /etc/cron.d/crontab

RUN /usr/bin/crontab /etc/cron.d/crontab

# run crond as main process of container
RUN touch /var/log/cron.log
CMD cron && tail -f /var/log/cron.log
